### ISSUE TITLE
private.h?

### ISSUE THREAD

**Issue by koskee** [majodi/ESP32-Smart-Alarm-Clock#1]
Project contains a reference to header file "private.h" (in constants.h) but lib and include directories seem to be empty and src directory does not have a file by this name either. Where does one find this file?

**Comment by majodi** [comment]
private.h contains keys and tokens for API's. It is flagged as gitignore so not in the repo on Github. The file contains the following (replace "private" with your own keys or tokens):

#define GCLOUD_KEY "private"
#define NEWS_API_KEY "private"
#define WEATHER_API_KEY "private"
#define OAUTH_CLIENT_ID1 "private"
#define OAUTH_CLIENT_SECRET1 "private"
#define OAUTH_REFRESH_TOKEN1 "private"
#define BLYNK_AUTH "private"
